import { Roboto } from "next/font/google";
import Header from "@/components/layout/Header";
import "./globals.css";
import Footer from "@/components/layout/Footer";

const roboto = Roboto({ subsets: ["latin"] , weight: ['300', '500', '700']});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// will be in everypage
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        {/* max width; mx-auto: auto center(margins on side) ; p-5 add padding 上下有space*/}
        <main className="max-w-4xl mx-auto border p-5">
          <Header />
          {children}
          <Footer />

        </main>
      </body>
    </html>
  );
}
